### ISSUE TITLE
Theme top banner obstructs heading when linking to header

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/documentation#14]
So the RTD allows links to goto anchors but this damn header we put in hides it and it gets confusing to the user. I pressed an anchor link and it took me here:

![screen shot 2018-03-04 at 1 02 44 pm](https://user-images.githubusercontent.com/10051386/36943064-916b41c0-1fac-11e8-841c-ea3b701f8c1d.png)

If the top banner was not there we would see the section title however we cannot. We need things to scroll extra by the size of the banner up at the top.

**Comment by efeefe** [comment]
Obsolete.
