### ISSUE TITLE
Created PGP key, but it says that I need to create PGP key

### ISSUE THREAD

**Issue by azretkenzhaliev** [subutai-io/documentation#33]
https://docs.subutai.io/Products/Bazaar/27_E2E_plugin.html

Looks like after all steps I have to click on my profile button -> CDN and then 

![image](https://user-images.githubusercontent.com/7948741/38479364-7d4e78f6-3be0-11e8-8af5-ccf5b8ad8a7f.png)

this thing pops up, but it is not explained in docs.

After that for some reason my PGP Key fingerprint reset, don't know why. I had to set it again, and then it worked normally. Overall process is pretty confusing.

**Comment by efeefe** [comment]
not a documentation issue, it seems.
