### ISSUE TITLE
Configuring BP to produce documentation for subutai-io

### ISSUE THREAD

**Issue by marcoarthur** [subutai-io/documentation#37]
Since we moved readthedocs to a BP ( https://github.com/subutai-blueprints/hackathon/issues/10 ). 
Step up to produce documentation (and host it) from the bp readthedocs instance, instead of virtual machine method of generating docs.

**Comment by marcoarthur** [comment]
Missing libs was causing readthedocs failed importing repository from github. Correcte this issue

**Comment by marcoarthur** [comment]
**Some important issues to use RTD for subutai documentation**

Our primary method didn't use the RTD instance, but RTD vagrant image.
RTD instance differs greatly from vagrant image. Its **build environment** depends on **docker image**  (https://docs.readthedocs.io/en/latest/builds.html) and when set on our container gives an error to pull it down:

<pre>
root@rtd-zHA:/srv/rtd/source# docker -D pull readthedocs/build:latest
latest: Pulling from readthedocs/build
22dc81ace0ea: Pull complete
1a8b3c87dba3: Pull complete
91390a1c435a: Pull complete
07844b14977e: Pull complete
b78396653dae: Pull complete
3633c8edd16c: Pull complete
5ffbf0839764: Pull complete
2779c0216fcb: Pull complete
9b325b5013d2: Pull complete
a5330d851207: Pull complete
f8299fe21e2b: Pull complete
6e84ffb8c359: Pull complete
ebb9131a426c: Download complete
ebb9131a426c: Extracting [==================================================>]  654.6MB/654.6MB
e82d98168ea1: Download complete
8910d450357c: Download complete
e91e09282e14: Download complete
a8e6fe5262d0: Download complete
c3d4d1369246: Download complete
d5cdb53c0140: Download complete
477d8234a889: Download complete
7c8741cb7c73: Download complete
c0b04d4f9db7: Download complete
2a0cfa3e6b54: Download complete
47090fcb2eaa: Download complete
3b379203817d: Download complete
e36913502e9c: Download complete
e754ed5795b0: Download complete

failed to register layer: ApplyLayer exit status 1 stdout:  stderr: operation not permitted
</pre>

When tracking down reasons for failure found that could be related to this issue https://github.com/lxc/lxd/issues/3601 , that is related to lxc container settings.

So, we could not setup at moment a BP that is able to build documentation. But we could of course setup one of our servers for this use. So it could be a server.

On other hand, there is also some failures on installation libs that conflicts with **allauth** 
<pre>
Requirement already satisfied: pytz==2018.4 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 58)) (2018.4)
Requirement already satisfied: beautifulsoup4==4.6.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 59)) (4.6.0)
Requirement already satisfied: Unipath==1.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 60)) (1.1)
Requirement already satisfied: django-kombu==0.9.4 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 61)) (0.9.4)
Requirement already satisfied: mimeparse==0.1.3 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 62)) (0.1.3)
Requirement already satisfied: mock==2.0.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 63)) (2.0.0)
Requirement already satisfied: stripe==1.20.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 67)) (1.20.2)
Requirement already satisfied: django-formtools==2.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 69)) (2.1)
Requirement already satisfied: docker==3.1.3 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 75)) (3.1.3)
Requirement already satisfied: django-textclassifier==1.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 77)) (1.0)
Requirement already satisfied: django-annoying==0.10.4 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 78)) (0.10.4)
Requirement already satisfied: django-messages-extends==0.6.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 79)) (0.6.0)
Requirement already satisfied: djangorestframework-jsonp==1.0.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 80)) (1.0.2)
Requirement already satisfied: django-taggit==0.22.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 81)) (0.22.2)
Requirement already satisfied: dj-pagination==2.3.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 82)) (2.3.2)
Requirement already satisfied: sphinxcontrib-httpdomain==1.6.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 85)) (1.6.1)
Requirement already satisfied: commonmark==0.5.5 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 89)) (0.5.5)
Requirement already satisfied: recommonmark==0.4.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 91)) (0.4.0)
Requirement already satisfied: packaging==17.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 94)) (17.1)
Requirement already satisfied: django-cors-middleware==1.3.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 97)) (1.3.1)
Requirement already satisfied: nilsimsa==0.3.8 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 98)) (0.3.8)
Requirement already satisfied: user-agents<1.2.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from -r requirements/pip.txt (line 101)) (1.1.0)
Requirement already satisfied: sphinxcontrib-websupport in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (1.1.0)
Requirement already satisfied: typing; python_version < "3.5" in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (3.6.4)
Requirement already satisfied: setuptools in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (40.0.0)
Requirement already satisfied: imagesize in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (1.0.0)
Requirement already satisfied: babel!=2.0,>=1.3 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (2.6.0)
Requirement already satisfied: snowballstemmer>=1.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (1.2.1)
Requirement already satisfied: Jinja2>=2.3 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (2.10)
Requirement already satisfied: alabaster<0.8,>=0.7 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (0.7.11)
Requirement already satisfied: livereload>=2.5.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from mkdocs==0.17.3->-r requirements/pip.txt (line 11)) (2.5.2)
Requirement already satisfied: PyYAML>=3.10 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from mkdocs==0.17.3->-r requirements/pip.txt (line 11)) (3.13)
Requirement already satisfied: Markdown>=2.3.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from mkdocs==0.17.3->-r requirements/pip.txt (line 11)) (2.6.11)
Requirement already satisfied: click>=3.3 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from mkdocs==0.17.3->-r requirements/pip.txt (line 11)) (6.7)
Requirement already satisfied: tornado<5.0,>=4.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from mkdocs==0.17.3->-r requirements/pip.txt (line 11)) (4.5.3)
Requirement already satisfied: python-mimeparse>=0.1.4 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from django-tastypie==0.13.0->-r requirements/pip.txt (line 18)) (1.6.0)
Requirement already satisfied: python-dateutil!=2.0,>=1.5 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from django-tastypie==0.13.0->-r requirements/pip.txt (line 18)) (2.7.3)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from requests==2.18.4->-r requirements/pip.txt (line 32)) (1.22)
Requirement already satisfied: idna<2.7,>=2.5 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from requests==2.18.4->-r requirements/pip.txt (line 32)) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from requests==2.18.4->-r requirements/pip.txt (line 32)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from requests==2.18.4->-r requirements/pip.txt (line 32)) (2018.4.16)
Requirement already satisfied: billiard<3.6.0,>=3.5.0.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from celery==4.1.1->-r requirements/pip.txt (line 39)) (3.5.0.4)
Requirement already satisfied: kombu<5.0,>=4.2.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from celery==4.1.1->-r requirements/pip.txt (line 39)) (4.2.1)
Requirement already satisfied: requests-oauthlib>=0.3.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from django-allauth==0.32.0->-r requirements/pip.txt (line 43)) (1.0.0)
Requirement already satisfied: python-openid>=2.2.5 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from django-allauth==0.32.0->-r requirements/pip.txt (line 43)) (2.2.5)
Requirement already satisfied: gitdb2>=2.0.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from GitPython==2.1.10->-r requirements/pip.txt (line 49)) (2.0.3)
Requirement already satisfied: simplejson>=2.1.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from pyelasticsearch==0.7.1->-r requirements/pip.txt (line 53)) (3.16.0)
Requirement already satisfied: cssselect>0.7.9 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from pyquery==1.4.0->-r requirements/pip.txt (line 54)) (1.0.3)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /srv/rtd/rtd_env/lib/python2.7/site-packages (from mock==2.0.0->-r requirements/pip.txt (line 63)) (1.0.2)
Requirement already satisfied: pbr>=0.11 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from mock==2.0.0->-r requirements/pip.txt (line 63)) (4.1.0)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /srv/rtd/rtd_env/lib/python2.7/site-packages (from docker==3.1.3->-r requirements/pip.txt (line 75)) (3.5.0.1)
Requirement already satisfied: websocket-client>=0.32.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from docker==3.1.3->-r requirements/pip.txt (line 75)) (0.48.0)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /srv/rtd/rtd_env/lib/python2.7/site-packages (from docker==3.1.3->-r requirements/pip.txt (line 75)) (1.0.22)
Requirement already satisfied: docker-pycreds>=0.2.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from docker==3.1.3->-r requirements/pip.txt (line 75)) (0.3.0)
Requirement already satisfied: nltk in /srv/rtd/rtd_env/lib/python2.7/site-packages (from django-textclassifier==1.0->-r requirements/pip.txt (line 77)) (3.3)
Requirement already satisfied: textblob in /srv/rtd/rtd_env/lib/python2.7/site-packages (from django-textclassifier==1.0->-r requirements/pip.txt (line 77)) (0.15.1)
Requirement already satisfied: pyparsing>=2.0.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from packaging==17.1->-r requirements/pip.txt (line 94)) (2.2.0)
Requirement already satisfied: ua-parser>=0.4.1 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from user-agents<1.2.0->-r requirements/pip.txt (line 101)) (0.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from Jinja2>=2.3->Sphinx==1.7.4->-r requirements/pip.txt (line 6)) (1.0)
Requirement already satisfied: singledispatch in /srv/rtd/rtd_env/lib/python2.7/site-packages (from tornado<5.0,>=4.1->mkdocs==0.17.3->-r requirements/pip.txt (line 11)) (3.4.0.3)
Requirement already satisfied: backports-abc>=0.4 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from tornado<5.0,>=4.1->mkdocs==0.17.3->-r requirements/pip.txt (line 11)) (0.5)
Requirement already satisfied: amqp<3.0,>=2.1.4 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from kombu<5.0,>=4.2.0->celery==4.1.1->-r requirements/pip.txt (line 39)) (2.3.2)
Requirement already satisfied: oauthlib>=0.6.2 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from requests-oauthlib>=0.3.0->django-allauth==0.32.0->-r requirements/pip.txt (line 43)) (2.1.0)
Requirement already satisfied: smmap2>=2.0.0 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from gitdb2>=2.0.0->GitPython==2.1.10->-r requirements/pip.txt (line 49)) (2.0.3)
Requirement already satisfied: vine>=1.1.3 in /srv/rtd/rtd_env/lib/python2.7/site-packages (from amqp<3.0,>=2.1.4->kombu<5.0,>=4.2.0->celery==4.1.1->-r requirements/pip.txt (line 39)) (1.1.4)
recommonmark 0.4.0 has requirement commonmark<=0.5.4, but you'll have commonmark 0.5.5 which is incompatible.
</pre>

So, currently the BP works only getting (importing) github projects, but not building the docs, so it is **useless for use to build documentation out-of-box**, that **was not clear on RTD docs itself**, that led us to currently confusion.

**Comment by efeefe** [comment]
Exploring an alternative path here - ditching RTD altogether and migrate to a grav-based website (#45)
