### ISSUE TITLE
Respond to changes in GitHub Wiki Git repos and G-Drive document changes

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/documentation#4]
Setup Jenkins to trigger builds when we get change notifications via GitHub webhooks and GDoc notifications of changes.

1. Need to figure out if webhooks are even offered for GitHub Wiki Git repositories, if not we're going to need a workaround maybe via post commit hooks or something.
2. Need to figure out how to have GDocs notify Jenkins when files under some folder are changed. I have no idea how this would work at this point, and need to take a look at the GDoc API documentation for Google Drive and Docs.

Can we use travis for all this?

**Comment by efeefe** [comment]
Obsolete.
