### ISSUE TITLE
UI - fine tuning

### ISSUE THREAD

**Issue by efeefe** [subutai-io/documentation#48]
Things we need to solve on UI:

- [x] The list ("li") [here](https://dev.docs.subutai.io/faqs) has no bullets
- [x] As discussed with @fernandoted , we need the top menu from Subutai.io to be shown in the documentation website too
- [x] The headings are messy - h2 is smaller than h3 and h4. h2 should be intermediate between h1 and h2 (duh)

 

I'll keep reporting here as I find.

**Comment by efeefe** [comment]
A new one here:

- [ ] Create CSS classes to resize and float images to right or left using GRAV Markdown

**Comment by efeefe** [comment]
@MarilizaC made some comments too:

- Remove numbering of sections in the left sidebar (the docs which use the "chapter" template, I think)
- Remove the label "Table of contents" from the TOCs
- Replace the Subutai logo on the top of the left sidebar for "Subutai Documentation". As the logo will be moving to the new top menu, I agree this makes sense.

**Comment by efeefe** [comment]
The css for 'code' is adding weird and unnecessary blank space on the right side:

![image](https://user-images.githubusercontent.com/119052/48622224-3b56b980-e98d-11e8-9911-09d46324efc6.png)

**Comment by efeefe** [comment]
When accessing a link pointing directly to an internal anchor (#), the corresponding headline disappears under the top menu.

Current it's this:

![image](https://user-images.githubusercontent.com/119052/48787083-41230680-eccf-11e8-9951-9e80e88e7171.png)

But should be this:

![image](https://user-images.githubusercontent.com/119052/48787160-6748a680-eccf-11e8-94d0-f5250331a5ce.png)

**Comment by fernandoted** [comment]
> The css for 'code' is adding weird and unnecessary blank space on the right side:
> 
> ![image](https://user-images.githubusercontent.com/119052/48622224-3b56b980-e98d-11e8-9911-09d46324efc6.png)
the space is to "copy to clipboard" icon.
fixed

**Comment by efeefe** [comment]
That's cool, just tested. Works even on mobile.

**Comment by fernandoted** [comment]
> When accessing a link pointing directly to an internal anchor (#), the corresponding headline disappears under the top menu.
> 
> Current it's this:
> 
> ![image](https://user-images.githubusercontent.com/119052/48787083-41230680-eccf-11e8-9951-9e80e88e7171.png)
> 
> But should be this:
> 
> ![image](https://user-images.githubusercontent.com/119052/48787160-6748a680-eccf-11e8-94d0-f5250331a5ce.png)

I adjusted applying a style on anchor, but with no classes. So, this adjustment works on <3>+<a>. We need to check the situations of the anchor link.

**Comment by efeefe** [comment]
problem on header:

![image](https://user-images.githubusercontent.com/119052/49287865-277b7f00-f486-11e8-925f-7cc74c3de124.png)

Reported by Lars on nov 28th.

**Comment by fernandoted** [comment]
> @MarilizaC made some comments too:
> 
> * Remove numbering of sections in the left sidebar (the docs which use the "chapter" template, I think)
> * Remove the label "Table of contents" from the TOCs
> * Replace the Subutai logo on the top of the left sidebar for "Subutai Documentation". As the logo will be moving to the new top menu, I agree this makes sense.

adjustments applied. The table of contents with no title was weird, so I keep "Overview" as the title (and not "Table of Contents).
